apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: production
  name: kube-metrics-prometheus-server
spec:
  template:
    spec:
      containers:
        - name: prometheus-server
          args:
            - --storage.tsdb.retention.time=30d
            - --config.file=/etc/config/prometheus.yml
            - --storage.tsdb.path=/data
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --web.enable-lifecycle